---
title: "Одномерные интегральные уравнения Фредгольма"
author: "Юрченков Иван Александрович"
date: "2023-06-09"
output: 
  html_document: 
    toc: yes
    highlight: haddock
    theme: readable
    fig_width: 8
    fig_height: 8
    fig_caption: yes
    number_sections: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Введение

В данном материале будут разобраны понятия интегральных уравнений Фредгольма, их виды, теоремы существования решения. 

# Интегральные уравнения Фредгольма

**Интегральным уравнением Фредгольма первого рода** называется уравнение с интегральным оператором следующего вида:

$$
\int\limits_{\Sigma} K(x, y) u(y) dy = f(y), \quad x \in \mathbb{R}^{n},
$$
где $K(x,y)$ --- ядро интегрального оператора Фредгольма, зависящее от пары аргументов; $\Sigma$ --- область решения задачи; $f(x)$ --- известная внешняя функция, зачастую моделирующая внешнее воздействие на систему; $u(x)$ --- неизвестная функция, поиск которой осуществляется в данной задаче.



**Интегральным уравнением Фредгольма второго рода** называется уравнение с интегральным оператором следующего вида:
$$
u(x) + \int\limits_{\Sigma} K(x, y) u(y) dy = f(y), \quad x \in \mathbb{R}^{n},
$$
где все члены уравнения также могут быть интерпретированы из уравнения Фредгольма первого рода. Основное отличие уравнений первого и второго рода состоит в наличии в левой части равенства неизвестной функции, добавляемой к интегральному оператору линейно. Данное обстоятельство порождает ряд интересных особенностей, связанных с теоремой существования решения интегрального уравнения Фредгольма второго рода, так называемой *Альтернативой Фредгольма*.

# Численный метод решения интегральных уравнений Фредгольма

# Задачи для решения

# Вопросы на защиту